/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aflame' at '6/12/16 5:20 PM' with Gradle 2.13
 *
 * @author aflame, @date 6/12/16 5:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
